update to 1.28.0
AnacondaRecipes/featuretools-feedstock pull request #1
Opened 2023-10-31 13:20 UTC by M-Waszkiewicz-Anaconda

request from snowflake, was supposed to go to snowflake channel, but actually it is update on existing package on default channel
!!!  It will not build until woodwork is moved to defaults
- [upstream](https://github.com/alteryx/featuretools)
- removed tests as there is cyclic dependency on composeml in tests, will get back to it once composeml is done

2023-11-02 13:43 UTC, JeanChristopheMorinPerso requested changes

2023-11-02 13:43 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - featuretools/tests
```suggestion
```
Tets are already part of the downloaded archive (see https://inspector.pypi.io/project/featuretools/1.28.0/packages/0f/17/a63f1e42e28f048fc6fec196d242cff44e8842564f6023363df965d9ac0a/featuretools-1.28.0.tar.gz/).

Also, removing this will make `test_get_featuretools_root` work.

2023-11-02 13:43 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - openblas  # [not win]
This is making me nervous. Why is this needed?

2023-11-02 13:43 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +  skip: true  # [s390x]
```suggestion
  skip: true  # [py<38 or s390x]
```

2023-11-02 13:43 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - wheel
```suggestion
    - wheel
    - setuptools
```
See https://github.com/alteryx/featuretools/blob/1498c9a9723deff9b049e4bb70a4859c70331942/pyproject.toml#L208-L213

2023-11-02 13:45 UTC, JeanChristopheMorinPerso requested changes

2023-11-02 13:45 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pytest -k "not test_get_featuretools_root"  # [not win]
```suggestion
    - pytest --pyargs featuretools -v -k "not test_nans"  # [win]
    - pytest --pyargs featuretools -v  # [not win]
```

2023-11-02 14:25 UTC, cbouss commented on recipe/meta.yaml
> +    - openblas  # [not win]
`test_nans` fails in the mkl configuration. This just selects the other numpy/scipy variant for the test.

2023-11-02 14:30 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - openblas  # [not win]
This should be clearly documented in a comment then.

2023-11-02 14:42 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
> +    - openblas  # [not win]
yes, I have put an extra comment for this

2023-11-02 15:17 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - holidays >=0.13, <0.33.0
```suggestion
    - holidays >=0.13,<0.33.0
```

2023-11-02 16:06 UTC, skupr-anaconda commented
An error on `win64`:
`docker 4.0.1 requires pypiwin32, which is not installed.`

2023-11-02 16:21 UTC, cbouss commented
> An error on `win64`: `docker 4.0.1 requires pypiwin32, which is not installed.`

FYI, it's the same issue we noticed on https://github.com/AnacondaRecipes/woodwork-feedstock/pull/2

2023-11-03 10:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
Errors were found

</details>

2023-11-03 11:58 UTC, skupr-anaconda approved these changes

2023-11-03 14:47 UTC, cbouss approved these changes
LGTM

2023-11-03 17:39 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
Errors were found

</details>

2023-11-03 22:55 UTC, merged

2023-11-03 22:56 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
Errors were found

</details>